apiVersion: v1
kind: Service
metadata:
  name: rust-actix
  labels:
    app: rust-actix
spec:
  selector:
    app: rust-actix
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP