apiVersion: v1
kind: Service
metadata:
  name: python-fastapi
  labels:
    app: python-fastapi
spec:
  selector:
    app: python-fastapi
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: debug
    port: 5678
    targetPort: 5678
    protocol: TCP
  type: ClusterIP