apiVersion: v1
kind: Service
metadata:
  name: go-gin
  labels:
    app: go-gin
spec:
  selector:
    app: go-gin
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: debug
    port: 2345
    targetPort: 2345
    protocol: TCP
  type: ClusterIP