apiVersion: v1
kind: Service
metadata:
  name: fsharp-giraffe
  labels:
    app: fsharp-giraffe
    framework: dotnet
    language: fsharp
    managed-by: k8s-remote-debug
spec:
  selector:
    app: fsharp-giraffe
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP